"""First-frame composite step for the UGC pipeline.

Calls Nano Banana 2 (Gemini 3 Flash Image) to generate a 1080x1920 PNG for
each clip in a video. See SPEC.md §5 step 4 for the full contract.

Cost estimate per image: $0.039 (midpoint of $0.02–$0.05 per SPEC.md §12).
Cost is recorded BEFORE each API call attempt so that a crash during the call
still appears in cost accounting on the next run.
"""

from __future__ import annotations

import base64
import hashlib
import pathlib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Protocol

import structlog
import tenacity

from ugc_pipeline.cost_tracker import increment_cost
from ugc_pipeline.models import ProductBrief, PromptVersion, RunState, VideoSpec, VideoState
from ugc_pipeline.prompts import first_frame as first_frame_prompt
from ugc_pipeline.state_manager import save_run_state, save_video_state

log = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# Exceptions  (SPEC.md §11)
# ---------------------------------------------------------------------------


class NanoBananaError(Exception):
    """Base error for Nano Banana 2 (Gemini 3 Flash Image) failures."""


class NanoBananaSafetyError(NanoBananaError):
    """Raised when the image generation request is rejected by a safety filter."""


class NanoBananaGenerationError(NanoBananaError):
    """Raised for transient or non-safety generation failures."""


# ---------------------------------------------------------------------------
# Result model
# ---------------------------------------------------------------------------


@dataclass
class NanoBananaResult:
    """Container for a successful image generation result."""

    png_bytes: bytes
    model: str = "gemini-3-pro-image-preview"


# ---------------------------------------------------------------------------
# Client protocol and default adapter
# ---------------------------------------------------------------------------


class NanoBananaClientProtocol(Protocol):
    """Minimal async interface for the Nano Banana 2 image generation API."""

    async def generate_image(
        self,
        *,
        prompt: str,
        model: str,
        reference_image_bytes: bytes | None = None,
        source_image_bytes: bytes | None = None,
        source_image_mime_type: str = "image/png",
    ) -> NanoBananaResult: ...


def _mime_from_path(path: pathlib.Path) -> str:
    """Return the MIME type for an image file based on its extension.

    Falls back to 'image/jpeg' for unknown extensions — the API tolerates this
    for common image formats.
    """
    ext = path.suffix.lower()
    return {
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
        ".webp": "image/webp",
        ".gif": "image/gif",
    }.get(ext, "image/jpeg")


def _build_generate_image_contents(
    prompt: str,
    source_image_bytes: bytes | None,
    source_image_mime_type: str,
    reference_image_bytes: bytes | None,
) -> list[dict]:
    """Build the ``contents`` list for a generate_content call (pure, no I/O).

    Order: source product image first (if any), talent reference image second
    (if any), then the text prompt. This matches the preamble order in the
    rendered prompt text and the INPUT_ORDER_NOTE in render_with_source_and_talent.

    The talent reference image is always a PNG produced by Nano Banana itself, so
    its MIME type is hardcoded to ``image/png``. The source product image MIME
    type is passed explicitly so PNG source images are not misidentified as JPEG.

    Extracted as a pure function so it can be unit-tested without constructing a
    real google.genai Client (which requires valid credentials).
    """
    parts: list[dict] = []
    if source_image_bytes is not None:
        src_b64 = base64.standard_b64encode(source_image_bytes).decode()
        parts.append({"inline_data": {"mime_type": source_image_mime_type, "data": src_b64}})
    if reference_image_bytes is not None:
        ref_b64 = base64.standard_b64encode(reference_image_bytes).decode()
        # Talent reference is always a PNG generated by this pipeline.
        parts.append({"inline_data": {"mime_type": "image/png", "data": ref_b64}})
    parts.append({"text": prompt})
    return [{"role": "user", "parts": parts}]


class _DefaultNanoBananaClient:
    """Default adapter wrapping google.genai for image generation.

    # TODO Day 8: validate against google-genai 2.0 image API surface.
    """

    def __init__(
        self,
        project: str,
        location: str,
        credentials_path: str,
    ) -> None:
        from google import genai  # type: ignore[import-untyped]
        from google.oauth2 import service_account  # type: ignore[import-untyped]

        credentials = service_account.Credentials.from_service_account_file(
            credentials_path,
            scopes=["https://www.googleapis.com/auth/cloud-platform"],
        )
        self._client = genai.Client(
            vertexai=True,
            project=project,
            location=location,
            credentials=credentials,
        )

    async def generate_image(
        self,
        *,
        prompt: str,
        model: str,
        reference_image_bytes: bytes | None = None,
        source_image_bytes: bytes | None = None,
        source_image_mime_type: str = "image/png",
    ) -> NanoBananaResult:
        """Call Nano Banana via google.genai and return a NanoBananaResult.

        Passes ``image_config(aspect_ratio="9:16")`` so the model is forced
        to portrait output rather than the default 1:1 square. Falls back to
        no config if the SDK version doesn't support ImageConfig.

        When *source_image_bytes* and/or *reference_image_bytes* are provided,
        they are prepended as inline_data parts before the text prompt in the
        user message. Order: source product image first, then talent reference
        image (if any), then the text prompt. This matches the preamble order
        in the rendered prompt text.

        The *source_image_mime_type* must match the actual file type of the
        source product image (derived from its extension via _mime_from_path).
        Using the wrong MIME type may cause the model to misdecode the bytes.
        """
        from google.genai import types  # type: ignore[import-untyped]

        config = None
        try:
            config = types.GenerateContentConfig(
                image_config=types.ImageConfig(aspect_ratio="9:16"),
                response_modalities=["IMAGE"],
            )
        except (AttributeError, TypeError):
            # Older SDK without ImageConfig — rely on prompt-text aspect hint only.
            pass

        contents = _build_generate_image_contents(
            prompt=prompt,
            source_image_bytes=source_image_bytes,
            source_image_mime_type=source_image_mime_type,
            reference_image_bytes=reference_image_bytes,
        )

        kwargs: dict = {
            "model": model,
            "contents": contents,
        }
        if config is not None:
            kwargs["config"] = config
        response = await self._client.aio.models.generate_content(**kwargs)
        try:
            # Extract PNG bytes from the first candidate's inline data
            part = response.candidates[0].content.parts[0]
            png_bytes: bytes = part.inline_data.data
        except (IndexError, AttributeError) as exc:
            raise NanoBananaGenerationError(
                f"Unexpected response shape from {model}: {exc}"
            ) from exc

        return NanoBananaResult(png_bytes=png_bytes, model=model)


def make_default_client(
    project: str,
    location: str,
    credentials_path: str,
) -> _DefaultNanoBananaClient:
    """Return the default Nano Banana 2 client adapter, authenticated via service account.

    Pass the returned object as the *client* argument to run_first_frame_for_clip.
    """
    return _DefaultNanoBananaClient(
        project=project,
        location=location,
        credentials_path=credentials_path,
    )


# ---------------------------------------------------------------------------
# Cost estimate
# ---------------------------------------------------------------------------

_IMAGE_COST_USD: float = 0.039  # flat per-image estimate; midpoint of $0.02–$0.05 (SPEC.md §12)


def estimate_first_frame_cost_usd() -> float:
    """Return the flat per-image cost estimate for Nano Banana 2.

    This is a midpoint estimate of the $0.02–$0.05 range documented in
    SPEC.md §12. Actual billing may differ; tune empirically after Day 8.
    """
    return _IMAGE_COST_USD


# ---------------------------------------------------------------------------
# Inner tenacity-wrapped API helper
# (Each retry attempt bills separately — cost is recorded inside _call_with_cost.)
# ---------------------------------------------------------------------------


def _make_tenacity_caller(
    client: NanoBananaClientProtocol,
    prompt: str,
    model: str,
    run_state: RunState,
    video_state: VideoState,
    global_max_usd: float,
    video_state_path: pathlib.Path,
    run_state_path: pathlib.Path,
    reference_image_bytes: bytes | None = None,
    source_image_bytes: bytes | None = None,
    source_image_mime_type: str = "image/png",
) -> Any:
    """Return an awaitable that retries the image API call up to 5 times.

    Cost is recorded BEFORE each attempt (per SPEC.md §12 protocol) so that
    a crash during any attempt still counts toward the budget. Tenacity re-raises
    on exhaustion.

    Only NanoBananaGenerationError and generic Exception trigger tenacity retries.
    NanoBananaSafetyError is NOT in the retry_if list — safety errors must be
    handled explicitly in the caller (single safety retry with softened prompt).
    """
    from ugc_pipeline.state_manager import _dump_model, write_state_atomic  # local import

    @tenacity.retry(
        stop=tenacity.stop_after_attempt(5),
        wait=tenacity.wait_exponential(multiplier=2, max=60),
        retry=tenacity.retry_if_exception_type(NanoBananaGenerationError),
        reraise=True,
    )
    async def _call() -> NanoBananaResult:
        # Bill AFTER the call so 4xx/5xx (no compute consumed) does not pollute
        # the cost tracker. SPEC.md §12 prefers bill-before for long-running ops
        # (Veo); image generation is a single round-trip, so post-billing is safe.
        result = await client.generate_image(
            prompt=prompt,
            model=model,
            reference_image_bytes=reference_image_bytes,
            source_image_bytes=source_image_bytes,
            source_image_mime_type=source_image_mime_type,
        )
        increment_cost(run_state, video_state, "first_frame_usd", _IMAGE_COST_USD, global_max_usd)
        write_state_atomic(video_state_path, _dump_model(video_state))
        write_state_atomic(run_state_path, _dump_model(run_state))
        return result

    return _call()


# ---------------------------------------------------------------------------
# Main per-clip entry point
# ---------------------------------------------------------------------------


async def run_first_frame_for_clip(
    spec: VideoSpec,
    brief: ProductBrief,
    clip_index: int,
    talent_descriptor: str,
    *,
    client: NanoBananaClientProtocol,
    video_state: VideoState,
    run_state: RunState,
    state_root: pathlib.Path,
    artifacts_root: pathlib.Path,
    global_max_usd: float = 50.0,
    dry_run: bool = False,
    model: str = "gemini-2.5-flash-image",
    product_size_hint: str | None = None,
    reference_image_bytes: bytes | None = None,
    source_image_bytes: bytes | None = None,
    source_image_mime_type: str = "image/png",
) -> pathlib.Path:
    """Generate a first-frame PNG for *clip_index* and return its local path.

    Parameters
    ----------
    spec:
        VideoSpec for the current video.
    brief:
        ProductBrief describing the product.
    clip_index:
        0-based index of the clip being processed.
    talent_descriptor:
        Human-readable talent description resolved from talent_pool.yaml.
    client:
        An object satisfying NanoBananaClientProtocol (real or mock).
    video_state:
        Mutable VideoState for this video; mutated in place and saved.
    run_state:
        Mutable RunState for this run; mutated in place and saved.
    state_root:
        Root of the state directory tree.
    artifacts_root:
        Root of the artifacts directory (e.g. Path("artifacts")).
    global_max_usd:
        Kill-switch threshold forwarded to increment_cost.
    dry_run:
        If True, skip the API call, log the prompt and estimated cost, and
        return the expected output path without creating it.
    reference_image_bytes:
        Optional PNG bytes of clip 0's first frame (talent identity anchor).
        Used for clips 1..N to maintain talent identity continuity.
    source_image_bytes:
        Optional bytes of the original product image (from brief.image_path).
        Used for ALL clips so the model renders the actual product (labels,
        colour, shape) rather than a generic representation.
    source_image_mime_type:
        MIME type of *source_image_bytes*. Must match the actual file extension
        of brief.image_path (e.g. ``"image/png"`` for a .png file). Derived
        from the path via _mime_from_path in the orchestrator. Defaults to
        ``"image/png"`` — the most common source format.
    """
    import time

    from ugc_pipeline.state_manager import (
        _dump_model,
        _run_state_path,
        _video_state_path,
        write_state_atomic,
    )

    t_start = time.monotonic()

    artifact_key = f"clip_{clip_index}_firstframe"
    out_path = artifacts_root / video_state.video_id / f"clip_{clip_index}_firstframe.png"

    video_state_path = _video_state_path(video_state.video_id, state_root)
    run_state_path = _run_state_path(run_state.run_id, state_root)

    # ------------------------------------------------------------------
    # 1. Idempotency check
    # ------------------------------------------------------------------
    existing_path_str = video_state.artifacts.get(artifact_key)
    if existing_path_str is not None:
        existing_path = pathlib.Path(existing_path_str)
        if existing_path.exists() and existing_path.stat().st_size > 0:
            log.info(
                "step_skipped_idempotent",
                step="first_frame_composite",
                video_id=video_state.video_id,
                clip_index=clip_index,
                artifact_key=artifact_key,
            )
            return existing_path

    # ------------------------------------------------------------------
    # 2. Render prompt and build PromptVersion
    # ------------------------------------------------------------------
    _render_kwargs: dict = {}
    if product_size_hint:
        _render_kwargs["product_size_hint"] = product_size_hint

    # Select the appropriate render function based on which references are provided.
    # source_image_bytes + reference_image_bytes → dual-reference (clip ≥1 with product ref)
    # source_image_bytes only → source-only reference (clip 0 with product ref)
    # reference_image_bytes only → legacy talent-only reference (backward compat)
    # neither → plain text prompt
    if source_image_bytes is not None and reference_image_bytes is not None:
        rendered_prompt = first_frame_prompt.render_with_source_and_talent(
            spec, brief, clip_index, talent_descriptor, **_render_kwargs
        )
    elif source_image_bytes is not None:
        rendered_prompt = first_frame_prompt.render_with_source(
            spec, brief, clip_index, talent_descriptor, **_render_kwargs
        )
    elif reference_image_bytes is not None:
        rendered_prompt = first_frame_prompt.render_with_reference(
            spec, brief, clip_index, talent_descriptor, **_render_kwargs
        )
    else:
        rendered_prompt = first_frame_prompt.render(
            spec, brief, clip_index, talent_descriptor, **_render_kwargs
        )

    prompt_sha = hashlib.sha256(rendered_prompt.encode()).hexdigest()
    prompt_version = PromptVersion(
        step_name="first_frame_composite",
        version=first_frame_prompt.VERSION,
        content_sha256=prompt_sha,
        rendered_at=datetime.now(timezone.utc),
    )
    video_state.prompt_versions["first_frame"] = prompt_version

    # ------------------------------------------------------------------
    # 3. Dry-run short-circuit
    # ------------------------------------------------------------------
    if dry_run:
        log.info(
            "step_skipped_dryrun",
            step="first_frame_composite",
            video_id=video_state.video_id,
            clip_index=clip_index,
            estimated_cost_usd=estimate_first_frame_cost_usd(),
            rendered_prompt=rendered_prompt,
        )
        return out_path

    log.info(
        "step_started",
        step="first_frame_composite",
        video_id=video_state.video_id,
        clip_index=clip_index,
        artifact_key=artifact_key,
    )

    # ------------------------------------------------------------------
    # 4. Call with safety retry
    # ------------------------------------------------------------------
    # `model` is the kwarg above. Default is "gemini-2.5-flash-image" (Nano
    # Banana 1 / Gemini 2.5 Flash Image, GA, available in us-central1).
    # To use Gemini 3 Pro Image Preview ("Nano Banana 2") set
    # nano_banana.model: "gemini-3-pro-image-preview" AND
    # nano_banana.location: "global" in pipeline_config.yaml — the preview
    # is currently only served from the `global` Vertex AI endpoint.

    async def _attempt(
        prompt: str,
        ref_bytes: bytes | None = None,
        src_bytes: bytes | None = None,
    ) -> NanoBananaResult:  # type: ignore[return]
        """One attempt: bill + call, with tenacity on NanoBananaGenerationError."""
        return await _make_tenacity_caller(
            client=client,
            prompt=prompt,
            model=model,
            run_state=run_state,
            video_state=video_state,
            global_max_usd=global_max_usd,
            video_state_path=video_state_path,
            run_state_path=run_state_path,
            reference_image_bytes=ref_bytes,
            source_image_bytes=src_bytes,
            source_image_mime_type=source_image_mime_type,
        )

    try:
        result = await _attempt(rendered_prompt, reference_image_bytes, source_image_bytes)
    except NanoBananaSafetyError:
        # Single safety retry with softened prompt — bills again.
        # Both reference images (source and talent) are KEPT on retry — only the text is softened.
        log.warning(
            "step_safety_retry",
            step="first_frame_composite",
            video_id=video_state.video_id,
            clip_index=clip_index,
        )
        if source_image_bytes is not None and reference_image_bytes is not None:
            softened_prompt = first_frame_prompt.render_with_source_and_talent_softened(
                spec, brief, clip_index, talent_descriptor, **_render_kwargs
            )
        elif source_image_bytes is not None:
            softened_prompt = first_frame_prompt.render_with_source_softened(
                spec, brief, clip_index, talent_descriptor, **_render_kwargs
            )
        elif reference_image_bytes is not None:
            softened_prompt = first_frame_prompt.render_with_reference_softened(
                spec, brief, clip_index, talent_descriptor, **_render_kwargs
            )
        else:
            softened_prompt = first_frame_prompt.render_softened(
                spec, brief, clip_index, talent_descriptor, **_render_kwargs
            )
        # This attempt also bills via _attempt (which uses _make_tenacity_caller)
        result = await _attempt(softened_prompt, reference_image_bytes, source_image_bytes)

    # ------------------------------------------------------------------
    # 5. Persist artifact
    # ------------------------------------------------------------------
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(result.png_bytes)

    video_state.artifacts[artifact_key] = str(out_path.resolve())
    video_state.updated_at = datetime.now(timezone.utc)
    save_video_state(video_state, root=state_root)

    duration_ms = int((time.monotonic() - t_start) * 1000)
    log.info(
        "step_completed",
        step="first_frame_composite",
        video_id=video_state.video_id,
        clip_index=clip_index,
        artifact_path=str(out_path),
        duration_ms=duration_ms,
        cost_usd_cumulative=run_state.cumulative_cost_usd,
        prompt_versions={"first_frame": prompt_version.model_dump(mode="json")},
    )

    return out_path


# ---------------------------------------------------------------------------
# Multi-clip orchestrator helper
# ---------------------------------------------------------------------------


async def run_first_frames(
    spec: VideoSpec,
    brief: ProductBrief,
    talent_descriptor: str,
    *,
    client: NanoBananaClientProtocol,
    video_state: VideoState,
    run_state: RunState,
    state_root: pathlib.Path,
    artifacts_root: pathlib.Path,
    global_max_usd: float = 50.0,
    dry_run: bool = False,
    source_image_bytes: bytes | None = None,
) -> list[pathlib.Path]:
    """Generate first-frame PNGs for all clips in *spec* sequentially.

    Returns a list of paths in clip order (index 0 … clip_count-1).

    Parameters
    ----------
    source_image_bytes:
        Optional bytes of the original product image. When provided, it is
        passed to every clip call so the model renders the actual product
        (including labels and packaging details) rather than a generic shape.

    Note: Clip-level parallelism is the orchestrator's responsibility; this
    helper processes clips serially and is used in tests and the CLI.
    """
    paths: list[pathlib.Path] = []
    clip0_bytes: bytes | None = None
    for clip_index in range(spec.clip_count):
        # In dry_run, never pass a reference (file doesn't exist); otherwise chain
        # clip-0 bytes to all subsequent clips.
        ref = clip0_bytes if (clip_index >= 1 and not dry_run) else None
        # Source image is passed to all clips (or None in dry_run where we skip reads)
        src = source_image_bytes if not dry_run else None
        path = await run_first_frame_for_clip(
            spec=spec,
            brief=brief,
            clip_index=clip_index,
            talent_descriptor=talent_descriptor,
            client=client,
            video_state=video_state,
            run_state=run_state,
            state_root=state_root,
            artifacts_root=artifacts_root,
            global_max_usd=global_max_usd,
            dry_run=dry_run,
            reference_image_bytes=ref,
            source_image_bytes=src,
        )
        if clip_index == 0 and not dry_run:
            clip0_bytes = path.read_bytes()
        paths.append(path)
    return paths
